/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elsoGUI;
import java.io.*;
import java.awt.*;
import java.awt.event.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.script.ScriptEngineManager;
import javax.script.ScriptEngine;
import javax.script.ScriptException;
import java.lang.Math.*;


/**
 *
 * @author diak
 */
public class elso extends javax.swing.JFrame {
    
    double elsoszam;
    double masodikszam;
    double harmadikszam;
    double negyedikszam;
    double kiszamol;
    double eredmeny;
    String muvelet="";
    private Object math;
    
    
    

    /**
     * Creates new form elso
     */
    public elso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acgomb = new javax.swing.JButton();
        elojelgomb = new javax.swing.JButton();
        torles = new javax.swing.JButton();
        osztas = new javax.swing.JButton();
        szorzas = new javax.swing.JButton();
        kivonas = new javax.swing.JButton();
        osszeadas = new javax.swing.JButton();
        egyenlo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        kijelzo = new javax.swing.JLabel();
        kilences = new javax.swing.JButton();
        nyolcas = new javax.swing.JButton();
        hetes = new javax.swing.JButton();
        hatos = new javax.swing.JButton();
        otos = new javax.swing.JButton();
        negyes = new javax.swing.JButton();
        harmas = new javax.swing.JButton();
        kettes = new javax.swing.JButton();
        egyes = new javax.swing.JButton();
        nulla = new javax.swing.JButton();
        tizedes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        log = new javax.swing.JButton();
        nhatvany = new javax.swing.JButton();
        kethatvany = new javax.swing.JButton();
        haromhatvany = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        hex = new javax.swing.JButton();
        bin = new javax.swing.JButton();
        sinh = new javax.swing.JButton();
        cosh = new javax.swing.JButton();
        tanh = new javax.swing.JButton();
        szazalekgomb11 = new javax.swing.JButton();
        gyokvonas = new javax.swing.JButton();
        cbrc = new javax.swing.JButton();
        round = new javax.swing.JButton();
        octal = new javax.swing.JButton();
        Mod = new javax.swing.JButton();
        inx = new javax.swing.JButton();
        kepletvalaszto = new javax.swing.JComboBox<>();
        szamol = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        abevitel = new javax.swing.JTextField();
        bbevitel = new javax.swing.JTextField();
        kepletjel = new javax.swing.JLabel();
        eredmenyek = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mod = new javax.swing.JMenu();
        szamologep = new javax.swing.JMenuItem();
        tudomanyos = new javax.swing.JMenuItem();
        programozoi = new javax.swing.JMenuItem();
        kepletek = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Számológép");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(735, 490));

        acgomb.setBackground(new java.awt.Color(153, 153, 153));
        acgomb.setText("AC");
        acgomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acgombActionPerformed(evt);
            }
        });

        elojelgomb.setBackground(new java.awt.Color(153, 153, 153));
        elojelgomb.setText("+ / -");
        elojelgomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elojelgombActionPerformed(evt);
            }
        });

        torles.setBackground(new java.awt.Color(153, 153, 153));
        torles.setText("<--");
        torles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torlesActionPerformed(evt);
            }
        });

        osztas.setBackground(new java.awt.Color(255, 204, 102));
        osztas.setText("÷");
        osztas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osztasActionPerformed(evt);
            }
        });

        szorzas.setBackground(new java.awt.Color(255, 204, 102));
        szorzas.setText("x");
        szorzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szorzasActionPerformed(evt);
            }
        });

        kivonas.setBackground(new java.awt.Color(255, 204, 102));
        kivonas.setText("-");
        kivonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kivonasActionPerformed(evt);
            }
        });

        osszeadas.setBackground(new java.awt.Color(255, 204, 102));
        osszeadas.setText("+");
        osszeadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osszeadasActionPerformed(evt);
            }
        });

        egyenlo.setBackground(new java.awt.Color(255, 204, 102));
        egyenlo.setText("=");
        egyenlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egyenloActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        kijelzo.setBackground(new java.awt.Color(255, 255, 255));
        kijelzo.setFont(new java.awt.Font("Yu Gothic", 0, 36)); // NOI18N
        kijelzo.setForeground(new java.awt.Color(255, 255, 255));
        kijelzo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kijelzo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                kijelzoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kijelzo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kijelzo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        kilences.setBackground(new java.awt.Color(204, 204, 204));
        kilences.setText("9");
        kilences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilencesActionPerformed(evt);
            }
        });

        nyolcas.setBackground(new java.awt.Color(204, 204, 204));
        nyolcas.setText("8");
        nyolcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyolcasActionPerformed(evt);
            }
        });

        hetes.setBackground(new java.awt.Color(204, 204, 204));
        hetes.setText("7");
        hetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hetesActionPerformed(evt);
            }
        });

        hatos.setBackground(new java.awt.Color(204, 204, 204));
        hatos.setText("6");
        hatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hatosActionPerformed(evt);
            }
        });

        otos.setBackground(new java.awt.Color(204, 204, 204));
        otos.setText("5");
        otos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otosActionPerformed(evt);
            }
        });

        negyes.setBackground(new java.awt.Color(204, 204, 204));
        negyes.setText("4");
        negyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negyesActionPerformed(evt);
            }
        });

        harmas.setBackground(new java.awt.Color(204, 204, 204));
        harmas.setText("3");
        harmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harmasActionPerformed(evt);
            }
        });

        kettes.setBackground(new java.awt.Color(204, 204, 204));
        kettes.setText("2");
        kettes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kettesActionPerformed(evt);
            }
        });

        egyes.setBackground(new java.awt.Color(204, 204, 204));
        egyes.setText("1");
        egyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egyesActionPerformed(evt);
            }
        });

        nulla.setBackground(new java.awt.Color(204, 204, 204));
        nulla.setText("0");
        nulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nullaActionPerformed(evt);
            }
        });

        tizedes.setBackground(new java.awt.Color(204, 204, 204));
        tizedes.setText(".");
        tizedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tizedesActionPerformed(evt);
            }
        });

        jLabel2.setText("Számológép projekt: v 1.2 ");

        log.setBackground(new java.awt.Color(0, 153, 153));
        log.setText("Log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        nhatvany.setBackground(new java.awt.Color(0, 153, 153));
        nhatvany.setText("x^y");
        nhatvany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhatvanyActionPerformed(evt);
            }
        });

        kethatvany.setBackground(new java.awt.Color(0, 153, 153));
        kethatvany.setText("x^2");
        kethatvany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kethatvanyActionPerformed(evt);
            }
        });

        haromhatvany.setBackground(new java.awt.Color(0, 153, 153));
        haromhatvany.setText("x^3");
        haromhatvany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haromhatvanyActionPerformed(evt);
            }
        });

        sin.setBackground(new java.awt.Color(0, 153, 153));
        sin.setText("Sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        cos.setBackground(new java.awt.Color(0, 153, 153));
        cos.setText("Cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        tan.setBackground(new java.awt.Color(0, 153, 153));
        tan.setText("Tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        hex.setBackground(new java.awt.Color(255, 51, 51));
        hex.setText("Hex");
        hex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexActionPerformed(evt);
            }
        });

        bin.setBackground(new java.awt.Color(255, 51, 51));
        bin.setText("Bin");
        bin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binActionPerformed(evt);
            }
        });

        sinh.setBackground(new java.awt.Color(0, 153, 153));
        sinh.setText("Sinh");
        sinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinhActionPerformed(evt);
            }
        });

        cosh.setBackground(new java.awt.Color(0, 153, 153));
        cosh.setText("Cosh");
        cosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coshActionPerformed(evt);
            }
        });

        tanh.setBackground(new java.awt.Color(0, 153, 153));
        tanh.setText("Tanh");
        tanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanhActionPerformed(evt);
            }
        });

        szazalekgomb11.setBackground(new java.awt.Color(0, 153, 153));
        szazalekgomb11.setText("%");
        szazalekgomb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szazalekgomb11ActionPerformed(evt);
            }
        });

        gyokvonas.setBackground(new java.awt.Color(0, 153, 153));
        gyokvonas.setText("Gyök");
        gyokvonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gyokvonasActionPerformed(evt);
            }
        });

        cbrc.setBackground(new java.awt.Color(0, 153, 153));
        cbrc.setText("Cbrt");
        cbrc.setMaximumSize(new java.awt.Dimension(63, 23));
        cbrc.setMinimumSize(new java.awt.Dimension(63, 23));
        cbrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrcActionPerformed(evt);
            }
        });

        round.setBackground(new java.awt.Color(0, 153, 153));
        round.setText("Round");
        round.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundActionPerformed(evt);
            }
        });

        octal.setBackground(new java.awt.Color(255, 51, 51));
        octal.setText("Oct");
        octal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octalActionPerformed(evt);
            }
        });

        Mod.setBackground(new java.awt.Color(255, 51, 51));
        Mod.setText("Mod");
        Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModActionPerformed(evt);
            }
        });

        inx.setBackground(new java.awt.Color(255, 51, 51));
        inx.setText("Inx");
        inx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inxActionPerformed(evt);
            }
        });

        kepletvalaszto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kepletvalaszto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Válassz képletet...", "Sebesség", "Út", "Idő" }));
        kepletvalaszto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kepletvalasztoActionPerformed(evt);
            }
        });

        szamol.setText("Számol");
        szamol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szamolActionPerformed(evt);
            }
        });

        clear.setText("Törlés");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        abevitel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abevitelActionPerformed(evt);
            }
        });

        bbevitel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbevitelActionPerformed(evt);
            }
        });

        kepletjel.setBackground(new java.awt.Color(204, 204, 204));
        kepletjel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kepletjel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kepletjel.setToolTipText("");
        kepletjel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                kepletjelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        eredmenyek.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eredmenyek.setText("Eredmény:");

        mod.setText("Módok");

        szamologep.setText("Számológép");
        szamologep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szamologepActionPerformed(evt);
            }
        });
        mod.add(szamologep);

        tudomanyos.setText("Tudományos mód");
        tudomanyos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tudomanyosActionPerformed(evt);
            }
        });
        mod.add(tudomanyos);

        programozoi.setText("Szám rendszerek");
        programozoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programozoiActionPerformed(evt);
            }
        });
        mod.add(programozoi);

        kepletek.setText("Képet számítás");
        kepletek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kepletekActionPerformed(evt);
            }
        });
        mod.add(kepletek);

        jMenuBar1.add(mod);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(acgomb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(torles, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(elojelgomb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(osztas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(hetes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nyolcas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kilences, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(negyes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(otos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hatos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(egyes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kettes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(harmas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(osszeadas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kivonas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(szorzas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nulla, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tizedes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(egyenlo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(szazalekgomb11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sinh, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nhatvany, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tanh, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(kethatvany, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(round, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(haromhatvany, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbrc, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(gyokvonas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cosh, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Mod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hex, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(octal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(abevitel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bbevitel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(szamol, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kepletvalaszto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(kepletjel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(eredmenyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(kepletvalaszto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acgomb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(torles, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(osztas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elojelgomb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(szazalekgomb11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbevitel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abevitel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhatvany, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(octal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(szorzas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kilences, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nyolcas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hetes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eredmenyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gyokvonas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cosh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hex, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(negyes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(otos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hatos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kivonas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(kepletjel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(round, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kethatvany, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(harmas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kettes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(egyes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(osszeadas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nulla, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tizedes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(egyenlo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(haromhatvany, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbrc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(szamol, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acgombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acgombActionPerformed
        // TODO add your handling code here:
        kijelzo.setText("");
        elsoszam =0;
        masodikszam =0;
        eredmeny =0;
        muvelet ="";
        
    }//GEN-LAST:event_acgombActionPerformed

    private void hetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hetesActionPerformed
        // TODO add your handling code here:
                String tarolo = kijelzo.getText()+7;
        kijelzo.setText(tarolo);
    }//GEN-LAST:event_hetesActionPerformed

    private void nyolcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyolcasActionPerformed
        // TODO add your handling code here:
                String tarolo = kijelzo.getText()+8;
        kijelzo.setText(tarolo);
    }//GEN-LAST:event_nyolcasActionPerformed

    private void kilencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilencesActionPerformed
        // TODO add your handling code here:
                String tarolo = kijelzo.getText()+9;
        kijelzo.setText(tarolo);
    }//GEN-LAST:event_kilencesActionPerformed

    private void negyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negyesActionPerformed
        // TODO add your handling code here:
                String tarolo = kijelzo.getText()+4;
        kijelzo.setText(tarolo);
    }//GEN-LAST:event_negyesActionPerformed

    private void otosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otosActionPerformed
        // TODO add your handling code here:
                String tarolo = kijelzo.getText()+5;
        kijelzo.setText(tarolo);
    }//GEN-LAST:event_otosActionPerformed

    private void hatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hatosActionPerformed
        // TODO add your handling code here:
                String tarolo = kijelzo.getText()+6;
        kijelzo.setText(tarolo);
    }//GEN-LAST:event_hatosActionPerformed

    private void egyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egyesActionPerformed
        // TODO add your handling code here:
                String tarolo = kijelzo.getText()+1;
        kijelzo.setText(tarolo);
    }//GEN-LAST:event_egyesActionPerformed

    private void kettesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kettesActionPerformed
        // TODO add your handling code here:
                String tarolo = kijelzo.getText()+2;
        kijelzo.setText(tarolo);
    }//GEN-LAST:event_kettesActionPerformed

    private void harmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harmasActionPerformed
        // TODO add your handling code here:
                String tarolo = kijelzo.getText()+3;
        kijelzo.setText(tarolo);
    }//GEN-LAST:event_harmasActionPerformed

    private void nullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nullaActionPerformed
        // TODO add your handling code here:
                String tarolo = kijelzo.getText()+0;
        kijelzo.setText(tarolo);
    }//GEN-LAST:event_nullaActionPerformed

    private void osztasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osztasActionPerformed
        // TODO add your handling code here:
        elsoszam = Double.parseDouble(kijelzo.getText());
        muvelet="/";
        kijelzo.setText("");
    }//GEN-LAST:event_osztasActionPerformed

    private void tizedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tizedesActionPerformed
        if (!kijelzo.getText().contains("."))
        {
            kijelzo.setText(kijelzo.getText() + tizedes.getText());
        }
        
    }//GEN-LAST:event_tizedesActionPerformed

    private void szorzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szorzasActionPerformed
        // TODO add your handling code here:
        elsoszam = Double.parseDouble(kijelzo.getText());
        muvelet="*";
        kijelzo.setText("");
    }//GEN-LAST:event_szorzasActionPerformed

    private void kivonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kivonasActionPerformed
        // TODO add your handling code here:
        elsoszam = Double.parseDouble(kijelzo.getText());
        muvelet="-";
        kijelzo.setText("");
    }//GEN-LAST:event_kivonasActionPerformed

    private void osszeadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osszeadasActionPerformed
        // TODO add your handling code here:
        elsoszam = Double.parseDouble(kijelzo.getText());
        muvelet="+";
        kijelzo.setText("");
    }//GEN-LAST:event_osszeadasActionPerformed

    private void egyenloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egyenloActionPerformed
        // TODO add your handling code here:
        masodikszam = Double.parseDouble(kijelzo.getText());
        
                if (muvelet.equals("/")){
            eredmeny = elsoszam / masodikszam;
        }
                if (muvelet.equals("*")){
            eredmeny = elsoszam * masodikszam;
        }
                if (muvelet.equals("+")){
            eredmeny = elsoszam + masodikszam;
        }
                if (muvelet.equals("-")){
            eredmeny = elsoszam - masodikszam;
        }
        
                kijelzo.setText(String.valueOf(eredmeny));
        
    }//GEN-LAST:event_egyenloActionPerformed

    private void elojelgombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elojelgombActionPerformed
        // TODO add your handling code here:
          String tarolo = kijelzo.getText();
          int reszered = Integer.parseInt(tarolo)*(-1);
          kijelzo.setText(String.valueOf(reszered));
    }//GEN-LAST:event_elojelgombActionPerformed

    private void torlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torlesActionPerformed
        // TODO add your handling code here:
        String bsp = null;
        
        
        if(kijelzo.getText().length() > 0 )
        {
        StringBuilder strB = new StringBuilder(kijelzo.getText());
        strB.deleteCharAt(kijelzo.getText().length()-1);
        bsp = strB.toString();
        kijelzo.setText(bsp);
        }
        
    }//GEN-LAST:event_torlesActionPerformed

    private void szamologepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szamologepActionPerformed
        this.setResizable(true);
        this.setSize(245, 490);
    }//GEN-LAST:event_szamologepActionPerformed

    private void tudomanyosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tudomanyosActionPerformed
        this.setResizable(true);
        this.setSize(450, 490);
    }//GEN-LAST:event_tudomanyosActionPerformed

    private void programozoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programozoiActionPerformed
        this.setResizable(true);
        this.setSize(530, 490);
    }//GEN-LAST:event_programozoiActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = Math.log(ops);
        kijelzo.setText(String.valueOf(ops));
    }//GEN-LAST:event_logActionPerformed

    private void nhatvanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhatvanyActionPerformed
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = Math.pow(ops, ops);
        kijelzo.setText(String.valueOf(ops));   
    // TODO add your handling code here:
    }//GEN-LAST:event_nhatvanyActionPerformed

    private void kethatvanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kethatvanyActionPerformed
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = (ops * ops);
        kijelzo.setText(String.valueOf(ops));          // TODO add your handling code here:
    }//GEN-LAST:event_kethatvanyActionPerformed

    private void haromhatvanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haromhatvanyActionPerformed
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = (ops * ops * ops);
        kijelzo.setText(String.valueOf(ops));           // TODO add your handling code here:
    }//GEN-LAST:event_haromhatvanyActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = Math.sin(ops);
        kijelzo.setText(String.valueOf(ops));
    }//GEN-LAST:event_sinActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = Math.cos(ops);
        kijelzo.setText(String.valueOf(ops));
        // TODO add your handling code here:
    }//GEN-LAST:event_cosActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = Math.tan(ops);
        kijelzo.setText(String.valueOf(ops));
    }//GEN-LAST:event_tanActionPerformed

    private void hexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexActionPerformed
    int a = Integer.parseInt(kijelzo.getText());
    kijelzo.setText(Integer.toString(a,16));
    }//GEN-LAST:event_hexActionPerformed

    private void binActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binActionPerformed
    int a = Integer.parseInt(kijelzo.getText());
    kijelzo.setText(Integer.toString(a,2));
    }//GEN-LAST:event_binActionPerformed

    private void sinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinhActionPerformed
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = Math.sinh(ops);
        kijelzo.setText(String.valueOf(ops));
    }//GEN-LAST:event_sinhActionPerformed

    private void coshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coshActionPerformed
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = Math.cosh(ops);
        kijelzo.setText(String.valueOf(ops));       
        // TODO add your handling code here:
    }//GEN-LAST:event_coshActionPerformed

    private void tanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanhActionPerformed
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = Math.tanh(ops);
        kijelzo.setText(String.valueOf(ops));        
        // TODO add your handling code here:
    }//GEN-LAST:event_tanhActionPerformed

    private void szazalekgomb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szazalekgomb11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_szazalekgomb11ActionPerformed

    private void gyokvonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gyokvonasActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = Math.sqrt(ops);
        kijelzo.setText(String.valueOf(ops));
        
    }//GEN-LAST:event_gyokvonasActionPerformed

    private void kijelzoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_kijelzoAncestorAdded

    }//GEN-LAST:event_kijelzoAncestorAdded

    private void cbrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrcActionPerformed
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = Math.cbrt(ops);
        kijelzo.setText(String.valueOf(ops));
    }//GEN-LAST:event_cbrcActionPerformed

    private void roundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundActionPerformed
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = Math.round(ops);
        kijelzo.setText(String.valueOf(ops));
    }//GEN-LAST:event_roundActionPerformed

    private void octalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octalActionPerformed
            int a = Integer.parseInt(kijelzo.getText());
    kijelzo.setText(Integer.toString(a,8));
    }//GEN-LAST:event_octalActionPerformed

    private void ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModActionPerformed

    private void inxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inxActionPerformed
        double ops = Double.parseDouble(String.valueOf(kijelzo.getText()));
        ops = Math.log10(ops);
        kijelzo.setText(String.valueOf(ops));        // TODO add your handling code here:
    }//GEN-LAST:event_inxActionPerformed

    private void kepletekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kepletekActionPerformed
        this.setResizable(true);
        this.setSize(985, 490);
    }//GEN-LAST:event_kepletekActionPerformed

    private void abevitelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abevitelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abevitelActionPerformed

    private void bbevitelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbevitelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbevitelActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        
        abevitel.setText(null);
        bbevitel.setText(null);
        kepletjel.setText(null);
        kepletvalaszto.getSelectedItem().equals("Válassz képletet...");
        
        
        
    }//GEN-LAST:event_clearActionPerformed

    private void kepletvalasztoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kepletvalasztoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kepletvalasztoActionPerformed

    private void kepletjelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_kepletjelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_kepletjelAncestorAdded

    private void szamolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szamolActionPerformed
       
        negyedikszam = Double.parseDouble(kepletjel.getText());
        if ((abevitel.getText().equals(""))|| (bbevitel.getText().equals("")))
        {
        JOptionPane.showMessageDialog(null, "Adjon meg értékeket a számításhoz.",
                "Képletszámító", JOptionPane.INFORMATION_MESSAGE);
        }
        //út=sebesség*idő
        else if (kepletvalaszto.getSelectedItem().equals("Út"))
        {
            double harmadikszam = Double.parseDouble(abevitel.getText());
            double negyedikszam = Double.parseDouble(abevitel.getText());
            
            kiszamol = harmadikszam * negyedikszam;
        }
                
            kepletjel.setText(String.valueOf(kiszamol));
        
        
        
        
        
        
    }//GEN-LAST:event_szamolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(elso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(elso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(elso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(elso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new elso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mod;
    private javax.swing.JTextField abevitel;
    private javax.swing.JButton acgomb;
    private javax.swing.JTextField bbevitel;
    private javax.swing.JButton bin;
    private javax.swing.JButton cbrc;
    private javax.swing.JButton clear;
    private javax.swing.JButton cos;
    private javax.swing.JButton cosh;
    private javax.swing.JButton egyenlo;
    private javax.swing.JButton egyes;
    private javax.swing.JButton elojelgomb;
    private javax.swing.JTextField eredmenyek;
    private javax.swing.JButton gyokvonas;
    private javax.swing.JButton harmas;
    private javax.swing.JButton haromhatvany;
    private javax.swing.JButton hatos;
    private javax.swing.JButton hetes;
    private javax.swing.JButton hex;
    private javax.swing.JButton inx;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem kepletek;
    private javax.swing.JLabel kepletjel;
    private javax.swing.JComboBox<String> kepletvalaszto;
    private javax.swing.JButton kethatvany;
    private javax.swing.JButton kettes;
    private javax.swing.JLabel kijelzo;
    private javax.swing.JButton kilences;
    private javax.swing.JButton kivonas;
    private javax.swing.JButton log;
    private javax.swing.JMenu mod;
    private javax.swing.JButton negyes;
    private javax.swing.JButton nhatvany;
    private javax.swing.JButton nulla;
    private javax.swing.JButton nyolcas;
    private javax.swing.JButton octal;
    private javax.swing.JButton osszeadas;
    private javax.swing.JButton osztas;
    private javax.swing.JButton otos;
    private javax.swing.JMenuItem programozoi;
    private javax.swing.JButton round;
    private javax.swing.JButton sin;
    private javax.swing.JButton sinh;
    private javax.swing.JButton szamol;
    private javax.swing.JMenuItem szamologep;
    private javax.swing.JButton szazalekgomb11;
    private javax.swing.JButton szorzas;
    private javax.swing.JButton tan;
    private javax.swing.JButton tanh;
    private javax.swing.JButton tizedes;
    private javax.swing.JButton torles;
    private javax.swing.JMenuItem tudomanyos;
    // End of variables declaration//GEN-END:variables
}
